sonar.projectKey=instalador-guis
sonar.projectName=Instalador de GUIs
sonar.organization=inditex
sonar.sources=InstaladorGuis/
sonar.tests=InstaladorGuis.Tests/
sonar.exclusions=**/obj/**,**/bin/**,**/Generated/**,**/*.g.cs,**/*.g.i.cs,**/Themes/Theme.xaml.cs
sonar.cs.opencover.reportsPaths=InstaladorGuis.Tests/TestResults/opencover.xml
sonar.sourceEncoding=UTF-8
sonar.core.codeCoveragePlugin=opencover
